version: '3.8'
services:
  petclinic:
    build:
      context: ./
      dockerfile: ./backend/spring-boot-petclinic/Dockerfile
    ports:
      - 8000:8000
      - 8080:8080
    depends_on:
      - mysqlserver
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/petclinic?createDatabaseIfNotExist=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    volumes:
      - ./backend/spring-boot-petclinic/:/app
    command: ./mvnw spring-boot:run

  # angular-frontend:
  #   build:
  #     context: ./frontend/angular-petclinic
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 4200:4200
  #   volumes:
  #     - ./frontend/angular-petclinic/:/usr/src/app

  mysqlserver:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true